//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDYUGIOH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDYugiohEntitiesEntities : DbContext
    {
        public BDYugiohEntitiesEntities()
            : base("name=BDYugiohEntitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carta> Cartas { get; set; }
        public virtual DbSet<Elemento> Elementos { get; set; }
        public virtual DbSet<Tipo> Tipos { get; set; }
    }
}
