//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDYUGIOH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int IdCartas { get; set; }
        public string Nome { get; set; }
        public string Elemento { get; set; }
        public int Nivel { get; set; }
        public string Tipo { get; set; }
        private int Ataque { get; set; }
        private int Defesa { get; set; }
        public int tipoCarta { get; set; }
        public int elementoCarta { get; set; }
    
        public virtual Elemento Elemento1 { get; set; }
        public virtual Tipo Tipo1 { get; set; }
    }
}
